# Generated by Django 5.1.3 on 2024-12-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='faceImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
