# Generated by Django 5.1.3 on 2024-12-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_employee_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInCheckOutTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_start_time', models.TimeField(blank=True, null=True)),
                ('check_in_end_time', models.TimeField(blank=True, null=True)),
                ('check_out_start_time', models.TimeField(blank=True, null=True)),
                ('check_out_end_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
