# Generated by Django 5.1.3 on 2025-01-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_checkincheckouttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
