# Generated by Django 5.1.3 on 2025-01-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_employee_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='reset_token',
        ),
    ]
